[[sessions]]
name = "foo"
windows = [
    "top",
    { name = "logs", cmd = "tail -f ~/.zshrc" },
    { name = "watch_dirs", working_dir = "~/Documents", cmd = "watch -n 5 ls" },
]

[[sessions]]
name = "bar"
windows = [ "top" ]
